[package]
name = "gebemula"
version = "0.1.0"
authors = ["Bruno Romero de Azevedo <brunodea@inf.ufsm.br>"]

[dependencies]
clippy = "*"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"
